# numpy

## 넘파이 배열
Numpy 는 파이썬 내장 모듈이 아니다.  
따라서 별도의 설치를 해야한다.  
하지만 우리는 아나콘다를 환경으로 꾸렸기 때문에 기본적으로 Numpy 패키지 설치 없이 사용할 수 있다.   

```python 
!conda list
```

숫자 데이터를 좀 더 쉽고 편리하게 다룰 수 있게 도와주는 패키지이다.   
숫자 데이터를 효과적으로 다룰 수 있기에 이 패키지들은 데이터를 주로 다루는데,   
데이터 과학 및 데이터 분석에 많이 사용되는 파이썬 패키지이다.    
numpy는 다차원 배열 자료구조인 ndarray(n - dimension array) 클래스를 지원하며 벡터와 행렬을 사용하는 선형대수 계산에 주로 사용된다.   
https://www.numpy.org

### **넘파이 배열이란?** 
순서가 있는 **같은 종류(type)** 의 데이터가 저장되는 자료형  

그럼 같은 종류를 같은 리스트를 활용해서 데이터 처리하면 안되나?  
굳이 새로운 넘파이를 안 배워도 파이썬 기본 시퀀스만으로도 가능한가?
- 리스트도 좋은 자료형이지만 넘파이 배열이 구조적으로 속도가 더 빠르고 메모리 적게 사용

Numpy Array: 크기가 고정(크기 변화가 없다) 데이터 크기만 알면 순서대로 자르면 된다. 타입 고정(타입 하나)
data: 이진 데이터
dimensions: 배열 구조 
strides: 증감
크기(type의 크기)


Python List
length: 시퀀스 길이
items: 요소(주소)

수많은 숫자 데이터를 하나의 리스트 시퀀스로 다루게 되면 넘파이 배열에 비하여 상대적으로 속도가 느리고 메모리를 많이 차지 하는 단점이 있다.  
넘파이 패키지의 배열을 사용하면 리스트에 비해 적ㅇㄴ 메모리로 많은 데이터를 빠르게 처리할 수 있다.   
다만 넘파이 배열은 많은 데이터를 다룰 수 있따는 점에서 리스트와 비스하지만 차이점도 있다.  
##### **차이점**
1. 모든 요소가 같은 자료형이어야 한다.   
2. 요소의 개수 바꿀 수 없다.   

배열의 연산은 C로 구현된 내부 반복문을 사용하기 때문에 파이썬 반복문에 비해 속도가 빠르며   
벡터화 연산을 이용하여 간단한 코드로도 복잡한 선형 대수 연산을 수행할 수 있다.   
또한 배열 인덱싱을 사용한 Query기능을 이요하여 간단한 코드로도 복잡한 수식 계산할 수 있다.   

### **넘파이 패키지 임포트 하기** 
배열을 사용하기 위해서는 다음과 같이 NumpPy패키지 임포트 
```python 
import numpy as np
```
넘파이 패키지는 np라는 별칭을 부여해서 사용

### **1차원 배열 만들기** 
넘파이 배열 객체인 ndarray는 n-dimensional array의 약자.    
1차원 배열, 2차원 배열, 3차원 배열 등의 다차원 배열 자료구조 지원  
우선은 1차원 배열 만드는 방법에 대해 알아보기   

넘파이의 array 메서드 인수로 시퀀스 자료형을 넣으면 ndarray 클래스 객체, 즉 넘파이 배열로 변환해준다.  
주로 튜플보단 리스트를 많이 사용   
만들어진 ndarray 객체의 표현식(representation)을 보면 바깥쪽에 array()란 것이 붙어있을 뿐 리스트와 동일한 구조처럼 보인다. 

In [7]:
!conda list


toml                      0.10.2             pyhd3eb1b0_0  
toolz                     0.11.1             pyhd3eb1b0_0  
tornado                   6.1              py38h2bbff1b_0  
tqdm                      4.59.0             pyhd3eb1b0_1  
traitlets                 5.0.5              pyhd3eb1b0_0  
typed-ast                 1.4.2            py38h2bbff1b_1  
typing_extensions         3.7.4.3            pyha847dfd_0  
ujson                     4.0.2            py38hd77b12b_0  
unicodecsv                0.14.1                   py38_0  
urllib3                   1.26.4             pyhd3eb1b0_0  
vc                        14.2                 h21ff451_1  
vs2015_runtime            14.27.29016          h5e58377_2  
watchdog                  1.0.2            py38haa95532_1  
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1                    py38_1  
werkzeug                  1.0.1              pyhd3eb1b0_0  
wheel                     0.36.2       

In [8]:
#numpy 임포트 
# jupyter lab에서 1회만 실행함녀 그 아래 코드에선 다 사용 가능 
import numpy as np
ar = np.array([_ for _ in range(10)])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

넘파이 배열 객체 속성 중 **shape** 사용하면 그 넘파이 배열의 모양 확인 가능   
아래의 예제 코드를 통해 생성한 배열의 모양과 차원 확인 가능   
개수가 10개인 1차원 배열이 생성된 것을 확인 가능   

In [4]:
ar.shape

(10,)

In [9]:
type(ar)

numpy.ndarray

리스트 자료형과 구조가 같아 보이지만 type 내장 함수로 생성한 넘파이 배열의 자료형을 살펴보면 그 타입이 numpy.ndarray임을 확인

리스트 자료형은 요소의 종류에 관계 없이, 또 개수에 제한 없이 삽입, 삭제, 수정할 수 있다.   
그러나 넘파이 배열 객체는 C언어의 배열처럼 메모리에서 연속적인 배치를 이루기 때문에 모든 요속 같은 자료형이어야 하고 개수가 명확해야 한다.   
이런 배열의 구조적 특징 때문에 요소에 대한 접근이 간단하고 그로 인해 요소에 대한 루프(반복문)를 효과적으로 수행 가능   

아래 예제를 보면 ar 변수에 담는 ndarray 객체를 만들기 위해 같은 타입인 정수를 요소로 갖는 리스트 활용  
ar2의 경우 살펴보면 정수와 실수가 혼합된 리스트를 활용하여 ndarray 객체를 생성하고 있다.    
앞서 정수와 실수의 연산과 같은 맥락으로 실수 타입으로 모두 선언된 것을 확인 가능(**표현 범위가 더 큰 자료형으로 변환**)  

In [10]:
ar = np.array([_ for _ in range(10)])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
ar2 = np.array([0.1, 5, 3, 12, 0.5])
ar2

array([ 0.1,  5. ,  3. , 12. ,  0.5])

In [13]:
ar2.dtype

dtype('float64')

In [ ]:
01010101 -> 8bits == 1byte

### 넘파이의 자료형
넘파이의 배열인 ndarray 클래스는 요소가 모두 같은 자료형을 가진다.   
np.array() 함수로 넘파이 배열을 만들 때 자료형을 명시적으로 작성하려면 키워드 인자로 dtype을 사용  
반대로 dtype 키워드 인수가 없으면 해당 데이터 자료형을 동적 타이핑   
그리고 만들어진 넘파이 배열의 자료형을 확인하려면 dtype 속성 활용  

In [14]:
import numpy as np
x = np.array([1, 2, 3])
x.dtype

dtype('int32')

In [16]:
x = np.array([1.0, 2.0, 3.0])
x.dtype

dtype('float64')

### numpy의 자료형
np.array() 메서드를 쓸 때 dtype 키워드 인수로 지정할 자료형의 값은 dtype 접두사와 바이트(혹은 글자수)를 나타내는 숫자를 조합한 문자열 형태로 축약해서 사용 가능   
예를 들어 "F8"은 8바이트 부동소수점 실수를 뜻하고 "U4"는 4글자 유니코드 문자열을 뜻한다.   
숫자를 생략하면 운영체제에 따라 알맞은 크기 지정 해줌   

|dtype접두사|설명|사용예제|
|:--|--:|--:|
|"?"|boolean|?(True, False)|
|"i"|int|i8(64비트)|
|"u"|unsigned int|u8(64비트)|
|"f"|float|f8(64비트)|
|"c"|complex|c16(128비트)|
|"O"|Object|O(객체에 대한 포인터)|
|"U"|Unicode string|U24(24 유니코드 글자)|



In [21]:
ar3 = np.array([_ for _ in range(3, 10, 3)], 'i8') # int8bytes --> 8*8bit
print(ar3)
print(ar3.dtype)

[3 6 9]
int64


In [20]:
ar4 = np.array([_ for _ in range(2, 10, 2)], 'f8')
print(ar4)
print(ar4.dtype)

[2. 4. 6. 8.]
float64


In [22]:
# 유니코드 8글자 자료형을 명시적으로 선언
# 그래서 시퀀스 자료형 중 제일 큰 값이 <U5이지만 <U8로 타입이 지정되었다. 
ar4 = np.array(["가나다라마","바사아","자","차카"], 'U5')
print(ar4)
print(ar4.dtype)

['가나다라마' '바사아' '자' '차카']
<U5


첫 번째 넘파이 배열에서 "f"를 활용하여 float로 dtype을 지정해줬다.    
dtype속성을 활용해 타입을 확인하니 32비트의 float형으로 생성된 것 확인 가능   
이 타입간 덧세 ㅁ연산의 결과는 숫자로 계산됨  
바로 아래 넘파이 배열에서는 유니코드 문자열을 타입으로 지정해서 생성  
1글자 이하의 글자들로 구성된 유니코드임을 추가적으로 설명   
유니코드 간 덧셈 연산은 concatenate의 결과를 보여준다.   

In [23]:
x = np.array([1, 2, 3], dtype = 'f')
x.dtype

dtype('float32')

In [24]:
x[0] + x[1]

3.0

In [25]:
x = np.array([1, 2, 3], dtype = 'U')
x.dtype

dtype('<U1')

In [26]:
x[0] + x[1]

'12'

넘파이에서는 무한대를 표현하기 위한 np.inf(infinity)와 정의할 수 없는 숫자를 나타내는 np.nan(not a number)을 사용 가능    
1과 0을 나누려고 하거나 0에 대한 로그 값을 계산하면 무한대인 np.inf이 나온다.    
0을 0으로 나누려고 시도하면 np.nan이 나온다.

In [27]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

<ipython-input-27-6ab12ec6e7a4>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
<ipython-input-27-6ab12ec6e7a4>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])


array([  0.,  inf, -inf,  nan])

In [28]:
np.log(0)

<ipython-input-28-f6e7c0610b57>:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [29]:
np.exp(-np.inf)

0.0

### **벡터화 연산(Vectorized Operation)**
넘파이 배열 객체는 배열의 각 요소에 대한 반복 연산을 하나의 명령어로 처리하는 벡터화 연산을 지원  

#### 리스트 연산
예를들어, 다음 처럼 리스트 내 모든 요소 데이터를 모두 2배 해야하는 경우 생각

In [31]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
answer = [2 * d for d in data]
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

#### 넘파이 연산
넘파이 배열 객체의 벡터화 연산을 사용하면 다음과 같이 for 반복문 없이 간단하게 단 한 번의 연산식으로 표현 가능   
계산 속도도 리스트 객체에 반복문을 사용해서 처리하는 것보다 훨씬 빠르다

In [32]:
x = np.array(data)
x 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
2*x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

파이썬 리스트 객체에 정수를 곱하면 객체의 크기가 곱한 숫자만큼 반복 증가한다   
넘파이 배열 객체는 벡터화 연산이 이뤄진다   
**두 차이점 반드시 기억하기**

In [34]:
list_samp = [_ for _ in range(3)]
print(list_samp * 5)

[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]


벡터와 연산은 비교 연산과 논리 연산을 포함한 모든 종류의 수학연산에 대해 적용된다. 

In [40]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [36]:
2* a + b

array([12, 24, 36])

In [37]:
a == 2

array([False,  True, False])

In [38]:
b > 10

array([False,  True,  True])

In [41]:
(a == 2) & (b > 10) # and는 안 되고 & 

array([False,  True, False])

### **2차원 배열 만들기**
2차원 배열은 수학에서 행렬(matrix)이라고 했다.   
행렬에서는 가로줄을 행(row) 하고 세로줄을(column)이라고 부른다.   
이와 비숫한 구조를 넘파이 배열을 통해 만들어 보겠다.   

다음과 같이 리스트를 중첩하여 리스트의 리스트를 이용해서 2차원 배열처럼 생성할 수 있다.   
안쪽 리스트의 길이는 행렬의 열의 수 즉 가로 크기가 되고, 바깥쪽 리스트의 길이는 행렬의 행의 수, 즉 세로 크기가 된다.   
2*3 배열 만들기 

In [42]:
c = np.array([[0, 1, 2], [2, 3, 4]])
c

array([[0, 1, 2],
       [2, 3, 4]])

In [51]:
# 행열의 모양
c.shape

(2, 3)

In [46]:
# 행의 개수
len(c)

2

In [49]:
# 열의 개수
len(c[0])

3

### **3차원 배열 만들기** 
깊이 * 행 * 열의 모양을 가진다.   
axis 0 = 깊이      
axis 1 = 행  
axis 2 = 열  

리스트의 리스트의 리스트 이용하면 3차원 배열 생성 가능   
2 * 3 * 4 배열 만들기 

In [58]:
# 2 x 3 x 4
d = np.array([[[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]],
             [[13, 14, 15, 16], 
             [17, 18, 19, 20], 
             [21, 22, 23, 24]]])
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

배열의 차원 및 크기를 구하는 더 간단한 방법은 ndim 속성과 shape 속성 이용하기   
ndim 속성은 배열의 차원, shape속성은 배열의 크기 반환  

In [59]:
print(a.ndim)
print(a.shape)

1
(3,)


In [60]:
print(c.ndim)
print(c.shape)

2
(2, 3)


In [61]:
print(d.ndim)
print(d.shape)

3
(2, 3, 4)


### **배열의 인덱싱**

In [62]:
a = np.array([0, 1, 2, 3, 4])

In [63]:
a[2]

2

In [64]:
a[-1]

4

2차원 배열의 인덱싱

다차원 배열일 때는 다음과 같이 콤마(,) 사용하여 접근 가능 
콤마로 구분된 차원을 축(axis)라고 한다. 그래프의 x축, y축으로 생각

In [69]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [71]:
a[0,0]

0

In [72]:
a[0, -1]

2

In [77]:
a[-1,-1]

5

2차원 리스트의 인덱싱

In [74]:
list_sample = [[0, 1, 2], [3, 4, 5]]

In [75]:
list_sample[0][0]

0

In [76]:
list_sample[0][1]

1

### **배열의 슬라이싱** 
배열 객체로 구현한 다차원 배열의 원소 중 복수 개를 접근하려면 일반적인 파이썬 슬라이싱과 콤마 함께 사용

In [78]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [88]:
# reshape으로도 2차원 배열 형태로 만들 수 있다
b = np.array([_ for _ in range(8)]).reshape(2, 4)
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [79]:
a[0, :] #첫번째 행 전체

array([0, 1, 2, 3])

In [80]:
a[:, 1] # 두번째 행 전체

array([1, 5])

In [81]:
a[1, 1:] # 두번째 행의 두번째 열부터 끝까지

array([5, 6, 7])

In [82]:
a[:2, :2]

array([[0, 1],
       [4, 5]])

### **배열 생성**
numpy에는 몇가지 단순한 배열을 생성하는 메서드를 제공
1. zeros, ones
2. zeros_like, ones_like
3. empty
4. arange
5. linspace, logspace
6. zeros

크리가 정해져있고 모든 값이 0인 배열을 생성하려면 zeros 메서드를 사용

크기를 뜻하는 튜플을 입력하면 다차원 배열 생성 가능

In [85]:
a= np.zeros(5) # float 타입으로 만들어진다
a

array([0., 0., 0., 0., 0.])

array 명령과 마찬가지로 dtype 인수 명시하면 해당 자료형 원소를 가진 배열 생성

In [84]:
c = np.zeros((5,2), dtype = 'i')
c


array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

문자열 배열도 가능하지만, 모든 원소의 문자열 크기가 같아야 한다.  
만약 더 큰 크기의 문자열 할당하면 잘릴 수 있다.

In [90]:
d = np.zeros(5, dtype = "U4")
d

array(['', '', '', '', ''], dtype='<U4')

In [91]:
d[0] = "abc"
d[1] = "abcd"
d[2] = "ABCDE"
d

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

0 이 아닌 1로 초기화된 배열을 생성하려면 ones 메서드 사용

In [93]:
e = np.ones((2, 3, 4), dtype = 'i8')
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

만약 크기를 튜플로 명시하지 않고 다른 배열과 같은 크기의 배열을 생성하고 싶다면 ones_like, zeros_like 명령 사용

In [95]:
f = np.ones_like(e, dtype = 'f' )
f h

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)

배열의 크기가 커지면 배열을 초기화하는데도 시간이 걸린다   
시간을 단축하려면 배열을 생성만 하고 특정한 값으로 초기화 하지 않는 empty 며령을 사용할 수 있다.   
empty 명령으로 생성된 배열에는 기존 메모리에 저장되어 있던 값이 있으므로 배열의 원소의 값을 미리 알 수 없다.  

In [97]:
g = np.empty((4,3))
g

array([[0.0078125, 0.0078125, 0.0078125],
       [0.0078125, 0.0078125, 0.0078125],
       [0.0078125, 0.0078125, 0.0078125],
       [0.0078125, 0.0078125, 0.0078125]])

In [100]:
 np.arange(10) # 0, ... n-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
np.arange(3, 21, 2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

linspace 명령이나 logspace 명령은 선형구간 혹은 로그 구간을 지정한 구간의 수만큼 분할 

In [109]:
# 개수에 맞춰서 등간격으로 맞춰준다
ex = np.linspace(0, 100, 20)
ex

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [110]:
ex2 = np.logspace(0, 100, 5)
ex2

array([1.e+000, 1.e+025, 1.e+050, 1.e+075, 1.e+100])

### 전치 연산
2차원 배열의 전치(tranpose) 연산은 행과 열을 바꾸는 작업.   
이는 배열의 T 속성을고 구할 수 있다. 메서드가 아니라 속성이라는 점에 유의

In [113]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [112]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### 배열의 크기 변형
일단 만들어진 배열의 내부 데이터는 보존한 채로 형태만 바꾸려면 reshpae 명령이나 메서드 사용  
예를 들어 12개의 원소인 1차원 배열은 3 \*4 크기의 2차원 배열로 만들 수 있다   
-1을 쓰면 해당숫자는 다른 값에서 ,,,,,,,

In [116]:
ex3 = np.arange(12)
ex3.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

다차원 배열을 1차원으로 만들기 위해서는 flatten() 혹은 ravel() 메서드 사용

In [118]:
ex3.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [119]:
ex3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

배열 사용에서 주의할 점은 길이가 5인 1차원 배열과 행, 열의 개수가 (5, 1)인 2차원 배열 또는 행, 열의 개수가 (1, 5)인 2차원 배열은 데이터가 같아도 엄연히 다른 객체

In [125]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

같은 배열에 대해 차원만 1차원 증가 시키는 경우에는 newaxis명령 사용

배열 연결
행의수나 열의 수가 같은 두개 이상의 배열을 연결하여 더 큰 배열을 만들때는 다음과 같은 명령 사용

- hstack
- vstack
- dstack
- stack
- r_
- c_
- tile

#### hstack
hstack 명령은 행의 수가 같은 두개 이상의 배열을 옆으로 연결하여 열의 수가 더 많은 배열을 만든다. 연결할 배열은 하나의 리스트에 담아야 한다. 

In [127]:
a1 = np.ones((2,3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [131]:
a2 = np.zeros((2, 2))
a2

array([[0., 0.],
       [0., 0.]])

In [133]:
np.hstack([a1, a2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

#### vstack
vstack 명령은 열의 수가 같은 두개 이상의 배열을 아래로 연결하여 행의 수가 더 많은 배열을 만든다. 연결할 배열은 하나의 리스트에 담아야 한다. 

In [134]:
b1 = np.ones((2,3))
b2 = np.zeros((3,3))

In [135]:
np.vstack([b1, b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### dstack
dstack 명령은 제 3의 축 즉, 행이나 열이 아닌 깊이 방향으로 배열을 합친다.  
가장 안쪽의 원소의 차원이 증가   
가장 내부의 숫자 원소가 배열이 된다  
shape 정보로 보자면 가장 끝에 값이 2인 차원이 추가된다  

In [136]:
c1 = np.ones((3,4))
c2 = np.zeros((3,4))

In [137]:
np.dstack([c1, c2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

#### stack
stack 명령은 dstack의 기능을 확장한 것으로 dstack처럼 마지막 차원으로 연결하는 것이 아니라   
사용자가 지정한 차원(축으로) 배열을 연결  
axis 인수(디폴트 0)를 사용하여 연결 후의 회전 방향을 정한다   
디폴트 인수값은 0이고 가장 앞쪽에 차원이 생성된다  
즉, 배열 두 개가 겹치게 되므로 연결하고자 하는 배열들의 크기가 모두 같아야 한다  

axis = 0 이므로 가장 바깥에 2인 차원이 추가 된다.  
즉, shape 변화는 2개의 (3 * 4)-> 1개의 (2 * 3 * 4)이다.  

In [145]:
c = np.stack([c1, c2])
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [146]:
c.shape

(2, 3, 4)

axis = 1로 설정  
즉, shape 변화는 2개의 (3 * 4)-> 1개의 (3 * 2 * 4)이다.  

In [143]:
c = np.stack([c1, c2], axis = 1)
c

array([[[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [0., 0., 0., 0.]]])

In [141]:
c.shape

(3, 2, 4)

#### r_ 메서드
r_ 메서드는 hstack 명령과 빘하게 배열을 좌우로 연결   
다만 메서드임에도 불구하고 소괄호 사용하지 않고 [] 대괄호 사용 특수메서드를 인덱서라고 한다

In [147]:
np.r_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([1, 2, 3, 4, 5, 6])

#### c_ 메서드
c_ 메서드는 배열의 차원을 증가시킨 후 좌우로 연결  
만약 1차원 배열을 연결하면 2차원 배열이 된다.

In [148]:
np.c_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

#### tile
동일한 배열을 반복하여 연결

In [150]:
a = np.array([[0, 1, 2], [3, 4, 5]])
np.tile(a, 2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [152]:
np.tile(a, (3,2)) # 행방향으로 3개 열 방향으로 2개

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])